---
name: Deploy GitHub Pages
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/30 * * * *"
permissions: {}
jobs:
  deploy-doc:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
    steps:
      - uses: suzuki-shunsuke/release-doc-action@69eaac9f74d1f9ef68bac65dd190f7ca30a99c12 # v0.0.2
        with:
          repository: suzuki-shunsuke/tfcmt-docs
          issue_number: 1724
          publish_dir: build
          destination_dir: docs
